version: '3.8'

services:
  postgres_database:
    image: postgres:15.2-alpine
    ports:
      - 58000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s 
      timeout: 5s 
      retries: 5
      start_period: 30s

  server:
    build: './fehu-server'
    ports:
      - 3000:3000
    env_file:
      - './fehu-server/.env'
    depends_on:
      postgres_database: 
        condition: service_healthy
