version: '3.8'

services:
  database:
    image: postgres:15.2-alpine
    ports:
      - 58000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s 
      timeout: 5s 
      retries: 5
      start_period: 30s
